[versions]
minSdk = "24"
targetSdk = "34"
compileSdk = "34"
versionCode = "11"
versionName = "2.0.2"
activityCompose = "1.9.1"
androidApplication = "8.5.1"
appcompat = "1.7.0"
composeBom = "2024.06.00"
composeCompiler = "1.5.14"
coilCompose = "2.5.0"
coreKtx = "1.13.1"
espressoCore = "3.6.1"
gradleKtlint = "12.0.3"
junit = "4.13.2"
koinAndroid = "3.5.3"
lifecycleViewmodelCompose = "2.8.4"
kotlin = "2.0.0"
material = "1.12.0"
navigationCompose = "2.7.7"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
android-material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
junit = { module = "junit:junit", version.ref = "junit" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koinAndroid" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidApplication" }
androidLibrary = { id = "com.android.library", version.ref = "androidApplication" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
gradle-ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "gradleKtlint" }